Dums 999 Server changes for the Chat
DTS-STN/scrum-poker-server pull request #36
Opened 2022-03-25 18:45 UTC by MarcoGoC

## Server changes for the chat

### Description
List of proposed changes:
- Updated server to pass pubsub as part of the context
- Message dataset along with schema, and resolvers 

### What to test for/How to test
- download and run. 
- open apollo studio 
- execute the subscription
- add a message  

### Additional Notes
- Edited and Delete Messages still under development

2022-03-25 19:19 UTC, DaceyTom2 requested changes, later dismissed
Looks really good!

2022-03-25 19:19 UTC, DaceyTom2 commented on api/message/subscriptions.js
> +    subscribe: (parent, args, { pubsub }) => {
A filter can be added to the subscribe so messages are only shared in one room

2022-03-25 19:19 UTC, DaceyTom2 commented on datasets/messages.js
> +  let id = new Date().getUTCMilliseconds() + Math.random().toString(10).slice(-5);
cool idea to use date as an id

2022-03-29 14:05 UTC, MarcoGoC commented on api/message/subscriptions.js
> +    subscribe: (parent, args, { pubsub }) => {
I tried and so far i could not make it work. it requires a rethought of everything. 
withFilter requires the single data item, and the second parameter is a Boolean that specifies whether the data should be posted or not. 
the issue here is the messages is an array that contains messages for potentially different rooms, as mention the whole  thing needs to be changed to use withFilter

2022-03-29 14:37 UTC, DaceyTom2 commented on api/message/subscriptions.js
> +    subscribe: (parent, args, { pubsub }) => {
Sounds good!

2022-03-29 14:38 UTC, DaceyTom2 approved these changes

2022-03-29 15:19 UTC, merged